Add Item Detail View page and Refactor ItemTable
DnD-Montreal/session-tome pull request #233
Opened 2022-01-09 07:07 UTC by luigibesani

Closes #193
Closes #124
## Description
- Implement the re-usable Component <DataTable> into the ItemTable Component in order to move away from a hard-coded table.
- Implement new ItemTable into the Inertia-rendered Item Page
- Add CharacterItemCreateForm component for Editing and Creating items
- Add ItemDetail Page

2022-01-10 15:20 UTC, willyyhuang commented on resources/js/Components/CharacterDetail/CharacterDetailBox.tsx
> +                            </Button>{' '}
remove `{' '}` please

2022-01-10 15:20 UTC, willyyhuang commented on resources/js/Components/ItemDetail/ItemDetailBox.tsx
> +                        {' '}
can you use ```{``}``` to merge these 2 lines into a single line

2022-01-10 15:20 UTC, willyyhuang commented on resources/js/Components/ItemDetail/ItemDetailBox.tsx
> +                    src='https://static.wikia.nocookie.net/eladriells-dd/images/d/d8/Orc.jpg/revision/latest/scale-to-width-down/600?cb=20190330101155'
this is a placeholder?

2022-01-10 22:36 UTC, pascwhale requested changes
Hey @luigibesani, everything works as intended but I do have some requests in terms of UI.

Item Detail Page
1- Can you replace the placeholder picture with a better one? The one we have for the character page is just fine.
2- Can you change how the rarity value is shown? You can look at my code for the DM Entry form from issue #211.
3- Can you align the breadcrumb component `Name`>`Item` to be on a single line? Also, can you follow the color pattern on the [mockups](https://www.figma.com/file/5uF4bHcHFTm13iMyrBzMt0/Designs-and-Mockups?node-id=593%3A24170)? The character name is a bit darker. I do appreciate the fact that you made the character name clickable!
4- Finally, this might be out of scope, but the search makes the table width change. Maybe that's something we can fix in a different issue if it's part of a custom component.

The team might also want to re-discuss whether we will allow a user to create magic items outside of (DM)Entries. I think that's all I have to say. I'll be happy to rereview the PR once the changes are done.

2022-01-11 02:40 UTC, willyyhuang approved these changes

2022-01-13 00:28 UTC, m-triassi commented
@luigibesani Please let us know if you're going to address @pascwhale's comments and resolve the merge conflicts

2022-01-15 17:09 UTC, willyyhuang commented on resources/js/Components/Form/ItemEditForm.tsx
> +                <StyledGrid item xs={12}>
can you use the same thing as me for rarity in `ItemForm`, rarity should be a select

2022-01-15 17:09 UTC, willyyhuang commented on resources/js/Components/Form/ItemEditForm.tsx
> +                                if (onCloseDrawer) {
this is not required, since onCloseDrawer is required

2022-01-15 19:36 UTC, pascwhale commented
![image](https://user-images.githubusercontent.com/43191176/149635375-f147ae42-4427-4944-a80a-e3692c6d8c67.png)
I tried importing a character from the `grod.csv` we've been using as an example. The Description field should avoid rendering anything below it.

Here's an example of when I manually attach an item through a DM Entry.
![image](https://user-images.githubusercontent.com/43191176/149635464-57b76a3e-79e9-4fa2-8287-d1b2659f1e20.png)
The field below it is empty. Maybe we can just put the words `No description` to provide some kind of feedback to the user.

Also, the word `DESCRPITION` is misspelled.

2022-01-15 21:13 UTC, willyyhuang approved these changes

2022-01-16 02:27 UTC, merged