Campaign Details Page
DnD-Montreal/session-tome pull request #404
Opened 2022-02-18 22:14 UTC by AnnieTran13

closes #394

2022-02-20 22:39 UTC, willyyhuang requested changes

2022-02-20 22:39 UTC, willyyhuang commented on resources/js/Components/Detail/CampaignDetail/CampaignDetailBox.tsx
> +    <Box sx={{p: 5, backgroundColor: 'primary'}}>
what's `p`

2022-02-20 22:39 UTC, willyyhuang commented on resources/js/Utils/index.ts
> +export {default as useEditDrawer} from './use-edit-drawer'
don't do this, I want to import hooks in the form of `import useEditDrawer from '@Utils/use-edit-drawer'
`

2022-02-21 00:19 UTC, closed without merging

2022-02-21 00:37 UTC, AnnieTran13 commented on resources/js/Components/Detail/CampaignDetail/CampaignDetailBox.tsx
> +    <Box sx={{p: 5, backgroundColor: 'primary'}}>
padding