Hide hard coded content
DnD-Montreal/session-tome pull request #517
Opened 2022-03-14 21:33 UTC by willyyhuang

2022-03-14 22:53 UTC, AnnieTran13 approved these changes

2022-03-17 00:29 UTC, m-triassi requested changes
Instead of commenting things out, can you just delete them instead? if you really need the code later it'll still be available in git

2022-03-17 00:30 UTC, willyyhuang commented
> Instead of commenting things out, can you just delete them instead? if you really need the code later it'll still be available in git

yaya okay

2022-03-17 00:55 UTC, m-triassi approved these changes
perfect!

2022-03-17 01:03 UTC, merged